apiVersion: v1
kind: Pod
metadata:
  name: bluewebdeploy
  labels:
    app: blueweb
spec:
  containers:
    - name: blueweb
      image: timpaniman/blue:1.1
---
kind: Service
apiVersion: v1
metadata:
  name: bluewebservice
spec:
  type: LoadBalancer
  selector:
    app: blueweb
  ports:
    - port: 8090
