kind: Pod
apiVersion: v1
metadata:
  name: bluewebdeploy
  labels:
    app: blueweb
spec:
  containers:
    - name: blueweb
      image: localhost:5000/blue:1.1
---
kind: Service
apiVersion: v1
metadata:
  name: bluewebservice
spec:
  selector:
    app: blueweb
  ports:
    - port: 8090
