apiVersion: apps/v1

kind: Deployment 

metadata:
  name: springboot
  labels:
    application: springboot

spec:
  selector:
    matchLabels:
      application: springboot 
  replicas: 3  
  template:
    metadata:
      name: springboot
      labels:
        application: springboot 
        env: dev 
        color: blue
      
    spec:
      containers:
        - name: blue
          image: varunmanik/springbootapp 
